services:
  product-service-db:
    image: docker.io/library/postgres:latest
    container_name: product-service-db
    hostname: product-service-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    networks:
      - product-service
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

  typesense:
    image: typesense/typesense:30.0.rc26
    container_name: typesense
    hostname: typesense
    ports:
      - "8108:8108"
    networks:
      - product-service
    volumes:
      - data:/typesense/data
    command: >
      --data-dir /typesense/data
      --api-key=${SE_API_KEY}
      --enable-cors
  
  typesense-dashboard:
    image: bfritscher/typesense-dashboard:latest
    container_name: typesense-dashboard
    hostname: typesense-dashboard
    ports:
      - "8109:80"
    networks:
      - product-service

networks:
  product-service:
    driver: bridge
volumes:
  data:
